export const ADD_GARDENPHOTO = 'ADD_GARDENPHOTO';
export const GET_GARDENPHOTO = 'GET_GARDENPHOTO';
export const SELECT_GARDENPHOTO = 'SELECT_GARDENPHOTO';
export const PHOTO_CLOSED = 'PHOTO_CLOSED';
export const MENU_OPEN = 'MENU_OPEN';
export const MENU_CLOSE = 'MENU_CLOSE';


