export const ADD_GARDENPHOTO = "ADD_GARDENPHOTO";
export const GET_GARDENPHOTO = "GET_GARDENPHOTO";
export const SELECT_GARDENPHOTO = "SELECT_GARDENPHOTO";
export const PHOTO_CLOSED = "PHOTO_CLOSED";
export const GARDEN_REVERSE = "GARDEN_REVERSE";
export const GARDEN_COLORSORT = "GARDEN_COLORSORT";
