# language: nix
services:
  - docker
sudo: required

env:
  - PROD=false
  - PROD=true

before_script:
  - mount
  - pwd
  - sysctl -a
  - env | grep NIX_
  - curl https://nixos.org/nix/install | sh
  - . ~/.nix-profile/etc/profile.d/nix.sh
  - nix-channel --update

script:
  - df -h
  - ./docker-build.sh --arg prod $PROD

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
