# language: nix
services:
  - docker
sudo: required

env:
  - PROD=false
  - PROD=true

before_script:
  - sudo mount -t tmpfs none /run/user -o remount,size=8G
  - curl https://nixos.org/nix/install | sh
  - . ~/.nix-profile/etc/profile.d/nix.sh
  - nix-channel --update

script:
  - ./docker-build.sh --arg prod $PROD

deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: etimo/photo-garden
    branch: master
    condition: "$PROD = true"
