language: nix
services:
- docker
sudo: required
env:
- PROD=false
- PROD=true
before_script:
- echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
- sudo mount -t tmpfs none /run/user -o remount,size=8G
- nix-channel --update
- nix-env -j32 -iA nixpkgs.git-crypt
- git crypt unlock git-crypt.key
- nix-env -j32 -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org
  --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
- cachix use photogarden
script:
- nix-build -j32 --arg prod $PROD | cachix push photogarden
- export DOCKER_TAG=$(git rev-parse HEAD)
- ./docker-build.sh --arg prod $PROD --argstr dockerImagePrefix $ECR_BASE --argstr dockerTag $DOCKER_TAG
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    repo: Etimo/photo-garden
    branch: master
    condition: "$PROD = true"
before_install:
- openssl aes-256-cbc -K $encrypted_8abf8cb4f491_key -iv $encrypted_8abf8cb4f491_iv
  -in git-crypt.key.enc -out git-crypt.key -d
