language: nix
services:
  - docker

# before_script: ./test.sh

env:
  - PROD=false
  - PROD=true

script:
  - ./docker-build.sh --arg prod $PROD

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
