# language: nix
services:
  - docker
sudo: required

# before_script: ./test.sh

env:
  - PROD=false
  - PROD=true

before_script:
  - curl https://nixos.org/nix/install | sh
  - . ~/.nix-profile/etc/profile.d/nix.sh
  - nix-channel --update

script:
  - ./docker-build.sh --arg prod $PROD

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
