notifications:
  email: false
language: node_js
node_js:
  - 8
sudo: required
services:
  - docker

install: no

before_script: ./test.sh

script: ./build.sh

after_success: 
  - ./push.sh
  - ./deploy.sh 
