language: nix
services:
- docker
sudo: required
env:
- PROD=false
- PROD=true
before_script:
- echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
- sudo mount -t tmpfs none /run/user -o remount,size=8G
- nix-channel --update
- nix-env -j32 -iA nixpkgs.git-crypt nixpkgs.cachix
- git crypt unlock git-crypt.key
- cachix use photogarden
script:
- nix-build --max-jobs 32 --arg prod $PROD --arg useDocker true --attr apps --attr jobs --attr dockerBuild.skopeoLoadMap --attr dockerBuild.skopeoUploadMap --attr dockerBuild.kubernetesConfig | cachix push photogarden
- export DOCKER_TAG=$(git rev-parse HEAD)
- ./docker-build.sh --arg prod $PROD
deploy:
  provider: script
  script: "./deploy.sh --arg prod $PROD --argstr dockerImagePrefix registry.kubernetes.etimo.se/photo-garden/ --argstr dockerTag $DOCKER_TAG"
  skip_cleanup: true
  on:
    repo: Etimo/photo-garden
    branch: master
    condition: "$PROD = true"
before_install:
- openssl aes-256-cbc -K $encrypted_8abf8cb4f491_key -iv $encrypted_8abf8cb4f491_iv
  -in git-crypt.key.enc -out git-crypt.key -d
