language: nix
services:
  - docker
sudo: required

env:
  - PROD=false
  - PROD=true

before_script:
  # /run/user is 100MB by default, which is not enough for Nix to build our Docker images
  - sudo mount -t tmpfs none /run/user -o remount,size=8G
  - nix-channel --update
  - nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
  - cachix use photogarden

script:
  - nix-build -j32 --arg prod $PROD | cachix push photogarden
  - ./docker-build.sh --arg prod $PROD

deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: Etimo/photo-garden
    branch: master
    condition: "$PROD = true"
