version: "2.1"
services:
  # External services
  queue:
    image: nats-streaming
    command: -m 8222 -store file -dir datastore
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    build: services/db
    ports:
      - "5433:5432"

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - photo-storage:/data
      - photo-storage-config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=not-so-access
      - MINIO_SECRET_KEY=not-so-secret

  minio-setup:
    build: services/minio-setup
    depends_on:
      - minio
    restart: on-failure
    environment:
      - MINIO_ACCESS_KEY=not-so-access
      - MINIO_SECRET_KEY=not-so-secret

  # Jobs
  db-migrations:
    depends_on:
      - db

  # Services
  gateway:
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
      - PHOTO_GARDEN_PROVIDERS_DROPBOX_CLIENT_ID
    depends_on:
      - queue
      - db
    ports:
      - "3000:3000"

  be-dropbox:
    depends_on:
      - queue
      - db

  be-process-exif:
    depends_on:
      - queue
      - db
      - minio
      - minio-setup

  be-download-user-photo:
    depends_on:
      - queue
      - minio
      - minio-setup

  be-google-drive:
    depends_on:
      - queue
      - db

  api-photos:
    ports:
      - "3002:3000"
    depends_on:
      - db

  web-frontend:
    ports:
      - "3001:1234"
      # HMR Websocket
      - "33710:33710"
    environment:
      - PHOTO_GARDEN_GATEWAY_BASE_URL=http://localhost:3000

volumes:
  photo-storage:
  photo-storage-config:
