version: "3.2"
services:
  db-migrations:
    build: db-migrations
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"

  db:
    build: db
    ports:
      - "5432:5432"

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_NAME: gateway
    volumes:
      - ${PWD}/apps:/usr/src/apps
      - ${PWD}/libs:/usr/src/libs
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
    depends_on:
      - queue
      - db
    links:
      - queue
      - db
    ports:
      - "3000:3000"

  photo-import:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        APP_NAME: photo-import
    volumes:
      - ${PWD}/apps:/usr/src/apps
      - ${PWD}/libs:/usr/src/libs
    depends_on:
      - queue
      - db
    links:
      - queue
      - db

  # photos_api:
  #   build: ./apps/photos
  #   volumes:
  #     - "./apps/photos/:/usr/src/app"
  #   depends_on:
  #     - db
  #     - queue
  #   links:
  #     - db
  #     - queue
  #   environment:
  #     - PGUSER=the_gardener
  #     - PGHOST=db
  #     - PGDATABASE=photo_garden
