FROM node:9.3-alpine

WORKDIR /usr/src

ARG APP_NAME

# Add repo dependencies to container
ADD libs libs
ADD yarn.lock .
ADD package.json .
ADD scripts scripts
ADD config.development.json .

# Add app to container
ADD apps/$APP_NAME apps/$APP_NAME

WORKDIR /usr/src/apps/$APP_NAME
RUN yarn install --no-progress
