version: "3"
services:
  admin:
    build: admin
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"

  db:
    build: db
    ports:
      - "5432:5432"

  gateway:
    build:
      context: ./apis/gateway
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CLIENT_REDIRECT_URI
    depends_on:
      - queue
    links:
      - queue
    volumes:
      - "./apis/gateway/:/usr/src/app"
    ports:
      - "3000:3000"

  photos_api:
    build: ./apis/photos
    volumes:
      - "./apis/photos/:/usr/src/app"
    depends_on:
      - db
      - queue
    links:
      - db
      - queue
    environment:
      - PGUSER=the_gardener
      - PGHOST=db
      - PGDATABASE=photo_garden
