version: "2.1"
services:
  # Other services
  db-migrations:
    build: services/db-migrations
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: nats-streaming
    command: -m 8222 -store file -dir datastore
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    build: services/db
    ports:
      - "5432:5432"

  services:
    build:
      context: .
      dockerfile: Dockerfile.backend-services.development
    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
    depends_on:
      - queue
      - db
    links:
      - queue
      - db
    ports:
      - "3000:3000"
      - "3001:1234"
      - "3002:3001"
