version: "3"
services:
  admin:
    build: admin
    command: ./setup-photo-garden.sh
    depends_on:
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"

  db:
    build: db
    ports:
      - "5432:5432"

  proxy:
    build: proxy
    ports:
      - "8080:80"
    depends_on:
      - providers
      - photos_api

  providers:
    build:
      context: ./providers
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CLIENT_REDIRECT_URI
    depends_on:
      - queue
    links:
      - queue
    volumes:
      - "./providers/:/usr/src/app"
    ports:
      - "3000"

  photos_api:
    build: apis/photos-api
    volumes:
      - "./apis/photos-api/:/usr/src/app"
    depends_on:
      - db
    environment:
      - PGUSER=the_gardener
      - PGHOST=db
      - PGDATABASE=photo_garden
