version: "2.1"
services:
  # Other services
  db-migrations:
    build: services/db-migrations
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: nats-streaming
    command: -m 8222 -store file -dir datastore
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    build: services/db
    ports:
      - "5432:5432"

  gateway:
    image: photo-garden-gateway:latest
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
      - PHOTO_GARDEN_PROVIDERS_DROPBOX_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_SECRET
      - LOG_LEVEL
    depends_on:
      - queue
      - db
    links:
      - queue
      - db
    ports:
      - "3000:3000"

  photo-server:
    build: services/photo-server
    environment:
      - LOG_LEVEL
    volumes:
      - photo-storage:/usr/share/nginx/html/
    ports:
      - "3010:80"

  be-dropbox:
    image: photo-garden-be-dropbox:latest
    environment:
      - LOG_LEVEL
    depends_on:
      - queue
      - db
    links:
      - queue
      - db

  be-process-exif:
    image: photo-garden-be-process-exif:latest
    environment:
      - LOG_LEVEL
    volumes:
      - photo-storage:/usr/src/photos
    depends_on:
      - queue
      - db
    links:
      - queue
      - db

  be-download-user-photo:
    image: photo-garden-be-download-user-photo:latest
    environment:
      - LOG_LEVEL
    volumes:
      - photo-storage:/usr/src/photos
    depends_on:
      - queue
    links:
      - queue

  be-instagram:
    image: photo-garden-be-instagram:latest
    environment:
      - LOG_LEVEL
    volumes:
      - photo-storage:/usr/src/photos
    depends_on:
      - queue
      - db
    links:
      - queue
      - db

  be-normalize-user-photo-google-drive:
    image: photo-garden-be-normalize-user-photo-google-drive:latest
    environment:
      - LOG_LEVEL
    depends_on:
      - queue
    links:
      - queue

  api-photos:
    image: photo-garden-api-photos:latest
    environment:
      - LOG_LEVEL
    ports:
      - "3002:3000"
    depends_on:
      - db
    links:
      - db

  web-frontend:
    image: photo-garden-web-frontend:latest
    environment:
      - LOG_LEVEL
    ports:
      - "3001:1234"

volumes:
  photo-storage:
