version: "3"
services:
  admin:
    build: admin
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"

  db:
    build: db
    ports:
      - "5432:5432"

  gateway:
    build: ./apis/gateway
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_REDIRECT_URI
    depends_on:
      - queue
      - db
    links:
      - queue
      - db
    ports:
      - "3000:3000"

  # photos_api:
  #   build: ./apis/photos
  #   volumes:
  #     - "./apis/photos/:/usr/src/app"
  #   depends_on:
  #     - db
  #     - queue
  #   links:
  #     - db
  #     - queue
  #   environment:
  #     - PGUSER=the_gardener
  #     - PGHOST=db
  #     - PGDATABASE=photo_garden
