version: "2.1"
services:
  # Other services
  db-migrations:
    build: services/db-migrations
    command: ./setup-photo-garden.sh
    depends_on:
      - db
    links:
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"

  db:
    build: services/db
    ports:
      - "5432:5432"

  # Apps
  gateway:
    extends:
      file: common-service.yml
      service: base-service
    build:
      args:
        APP_NAME: gateway
    environment:
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
      - PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
    depends_on:
      - queue
      - db
    links:
      - queue
      - db
    ports:
      - "3000:3000"

  be-photo-import:
    extends:
      file: common-service.yml
      service: base-service
    build:
      args:
        APP_NAME: be-photo-import
    depends_on:
      - queue
      - db
    links:
      - queue
      - db

  web-frontend:
    extends:
      file: common-service.yml
      service: base-service
    build:
      args:
        APP_NAME: web-frontend
    ports:
      - "3001:1234"

  api-photos:
    extends:
      file: common-service.yml
      service: base-service
    build:
      args:
        APP_NAME: api-photos
    depends_on:
      - db
    links:
      - db
    ports:
      - "3002:3000"
