FROM keymetrics/pm2:latest-alpine

WORKDIR /usr/src

# Add repo dependencies to container
COPY yarn.lock .
COPY package.json .
COPY scripts scripts
COPY config.development.json .

COPY libs libs
COPY apps apps

WORKDIR /usr/src/apps
RUN yarn install --no-progress

CMD ["pm2-runtime", "start", "ecosystem.config.js"]
