releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  version: 0.17.1
  set:
  - name: rbac.create
    value: true
- name: cert-manager
  namespace: kube-system
  chart: stable/cert-manager
  version: 0.5.0
  set:
  - name: createCustomResource
    value: true
- name: metrics-server
  namespace: kube-system
  chart: stable/metrics-server
  version: 2.0.2
- name: heapster
  namespace: kube-system
  chart: stable/heapster
  version: 0.3.1
- name: prometheus
  namespace: prometheus
  chart: stable/prometheus
  version: 7.1.3
  values:
  - nodeExporter:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
- name: grafana
  namespace: grafana
  chart: stable/grafana
  version: 1.14.8
  values:
  - datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.prometheus
    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 1Gi
    ingress:
      enabled: true
      hosts:
      - grafana.photo.garden
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      tls:
      - secretName: grafana-cert-secret
        hosts:
        - grafana.photo.garden
