apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: 255196862254.dkr.ecr.eu-west-1.amazonaws.com/etimo/photo-garden-web-frontend
        ports:
        - containerPort: 1234
