apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  selector:
    app: queue
  ports:
    - protocol: TCP
      name: queue-port
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: management-port
      port: 15672
      targetPort: 15672