apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
  name: photo-garden-ingress
spec:
  tls:
  - secretName: photo-garden-cert-secret
    hosts:
    - photo.garden
    - www.photo.garden
    - api.photo.garden
  rules:
  - host: photo.garden
    http:
      paths:
      - backend:
          serviceName: web-frontend
          servicePort: 1234
        path: /
  - host: www.photo.garden
    http:
      paths:
      - backend:
          serviceName: web-frontend
          servicePort: 1234
        path: /
  - host: api.photo.garden
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
        path: /
