apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: photo-garden-ingress
spec:
  tls:
  - secretName: photo-garden-cert-secret
  rules:
  - host: photo.garden
    http:
      paths:
      - backend:
          serviceName: web-frontend
          servicePort: 1234
        path: /
  - host: www.photo.garden
    http:
      paths:
      - backend:
          serviceName: web-frontend
          servicePort: 1234
        path: /
  - host: api.photo.garden
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
        path: /
