apiVersion: v1
kind: ServiceAccount
metadata:
  name: photo-garden
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: photo-garden
  labels:
    nats_cluster: nats-cluster
spec:
  permissions:
    publish: ["*"]
    subscribe: ["*"]
