apiVersion: apps/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
          - name: PHOTO_GARDEN_PROVIDERS_DROPBOX_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_PROVIDERS_DROPBOX_CLIENT_ID
          - name: PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_ID
          - name: PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_PROVIDERS_GOOGLE_DRIVE_CLIENT_SECRET
          - name: PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_ID
          - name: PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_PROVIDERS_INSTAGRAM_CLIENT_SECRET
        ports:
        - containerPort: 3000
