spec:
  template:
    spec:
      containers:
      - env:
          - name: PHOTO_GARDEN_DATABASES_GARDEN_HOST
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_DATABASES_GARDEN_HOST
          - name: PHOTO_GARDEN_DATABASES_GARDEN_PORT
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_DATABASES_GARDEN_PORT
          - name: PHOTO_GARDEN_DATABASES_GARDEN_USER
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_DATABASES_GARDEN_USER
          - name: PHOTO_GARDEN_DATABASES_GARDEN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_DATABASES_GARDEN_PASSWORD
          - name: PHOTO_GARDEN_DATABASES_GARDEN_DATABASE
            valueFrom:
              secretKeyRef:
                name: photo-garden-keys
                key: PHOTO_GARDEN_DATABASES_GARDEN_DATABASE
        ports:
        - containerPort: 3000
