spec:
  template:
    spec:
      containers:
      - env:
          - name: PHOTO_GARDEN_DATABASES_GARDEN_HOST
            valueFrom:
              configMapKeyRef:
                name: photo-garden-db
                key: host
          - name: PHOTO_GARDEN_DATABASES_GARDEN_PORT
            valueFrom:
              configMapKeyRef:
                name: photo-garden-db
                key: port
          - name: PHOTO_GARDEN_DATABASES_GARDEN_SSL_ENABLE
            value: "true"
          - name: PHOTO_GARDEN_DATABASES_GARDEN_USER
            valueFrom:
              secretKeyRef:
                name: photo-garden.photo-garden-garden.credentials
                key: username
          - name: PHOTO_GARDEN_DATABASES_GARDEN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: photo-garden.photo-garden-garden.credentials
                key: password
          - name: PHOTO_GARDEN_DATABASES_GARDEN_DATABASE
            valueFrom:
              configMapKeyRef:
                name: photo-garden-db
                key: database
        ports:
        - containerPort: 3000
